### ISSUE TITLE
群管理

### ISSUE THREAD

**Issue by reverland** [HalfdogStudio/wechat-user-bot#14]
- [x] 群用户列表，用户名抽取
- [x] ~~群拥有者~~
- [ ] 群操作（limited）

问题：

- ~~不能抽取我自己的群昵称？~~
- ~~群拥有者的名称抽取？~~

**Comment by hansnow** [comment]
更新太快，已然跟不上节奏

**Comment by jialincater** [comment]
**小寒粉丝团会师**

**Comment by reverland** [comment]
@hansnow @jialincater 去长亭科技面试估计就讲这个了。。。

**Comment by hansnow** [comment]
@reverland 酷！

**Comment by reverland** [comment]
群消息初步调研和设想？

1. 由于群名称、用户名都是加密/编码后的值，因此，能够获取和保存对应信息很必要。

和群有关的操作：

1. webwxsync收到消息，发送人是群(@@prefix username)



2. webwxsync收到modcontactList，会有变化的群名nickname、群名username，群拥有者username，nickname，displayname群名片

用户类似这样
,{
"Uin": xxxxx,
"UserName": "@28d497db0e8f87048880843d930818b5fa267313d3344e31759cf30104ead73c",
"NickName": "ZHANGYANG",
"AttrStatus": 102501,
"PYInitial": "",
"PYQuanPin": "",
"RemarkPYInitial": "",
"RemarkPYQuanPin": "",
"MemberStatus": 0,
"DisplayName": "",
"KeyWord": ""
}

群信息类似这样

,{
"UserName": "@@dc8c65c5350d088191435cdb1839dfafbef7dffa143e10cedaf9d0ab1b21945d",
"NickName": "滑雪票福利群1",
"Sex": 0,
"HeadImgUpdateFlag": 1,
"ContactType": 0,
"Alias": "",
"ChatRoomOwner": "@3eed375e89af35a3cc26092282d2a49a35d9ef4ebcdb5804b2c831a2a4cc57af",
"HeadImgUrl": "/cgi-bin/mmwebwx-bin/webwxgetheadimg?seq=0&username=@@dc8c65c5350d088191435cdb1839dfafbef7dffa143e10cedaf9d0ab1b21945d&skey=@crypt_3bb2969_5d9682fbe6794c9437337ef278f6615c",
"ContactFlag": 2,
"MemberCount": 100,
"MemberList": [{
"Uin": xxxxx,
"UserName": "@4d4e409acdfbfefaae0d2cf1764c7740142f01e4f73b88f7c1aded4ef3e5165f",
"NickName": "xxx",
"AttrStatus": 102503,
"PYInitial": "",
"PYQuanPin": "",
"RemarkPYInitial": "",
"RemarkPYQuanPin": "",
"MemberStatus": 0,
"DisplayName": "",
"KeyWord": ""
}

**Comment by reverland** [comment]
根据群username `@@XXXXXXXXXX` 获取群成员信息的方法 直接群名就行


     POST https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxbatchgetcontact?type=ex&r=1452862905530&lang=en_US&pass_ticket=KlRMZmPcELxJHikrTsq6UEuDiy%252BZn1wFQ1VoeVAHUls82tXXB4L89ePbSghP6ICI
200 OK 26 Kb 525 msec

{"BaseRequest":{"Uin":xxxxxx,"Sid":"L9W0ddcaijmzhYhu","Skey":"@crypt_3bb2969_5d9682fbe6794c9437337ef278f6615c","DeviceID":"e017670883684764"},"Count":2,"List":[{"UserName":"@@9dc894837da0c2ac9932a85afb91af2d085807013562857e8b4a0ca66661ec68","EncryChatRoomId":""},{"UserName":"@@69dfa612d6bbefebbf24c323b6103680ac32c6a7b41e0862cc24f0b6f3174a08","EncryChatRoomId":""}]}

返回
群信息、成员等，并有
"EncryChatRoomId": "@65bc6a3e6ae4bb4ba11cfc6e6fe6fec5"

**Comment by reverland** [comment]
webwxinit会获取一个chatset属性有许多最近联系的群和个人

之后batchgetcontact会使用这些信息

    {"BaseRequest":"Uin":2684027137,"Sid":"L9W0ddcaijmzhYhu","Skey":"@crypt_3bb2969_5d9682fbe6794c9437337ef278f6615c","DeviceID":"e320058942864127"},"Count":20,"List":{"UserName":"@@7b4640bd08b35f0e74dfcbbd5275d9ff8792a4a4d1c3b2f37ffc258b02c0bb84" ,"EncryChatRoomId":""},"UserName":"@7a4273ebf53cf3bb644e0331840585f7b54f8e5f3217caf72c7873f812990fea","EncryChatRoomId":""}]}

这个会返回详细群成员信息。

那如果是不再webwxinit获取的chatset内的群呢？

### websync收到系统消息

websync能接受手机上操作 msgtype51

&lt;msg&gt;<br/>&lt;op id='2'&gt;<br/>&lt;username&gt;2412069706@chatroom&lt;/username&gt;<br/>&lt;/op&gt;<br/>&lt;/msg&gt;

有个statusNotifyUsername @@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

之后会batchgetcontact 也会获得上述群信息

### websync收到modcontactlist存在

会返回变动的群信息。但不包含encrychatroomid或者chatroomid群聊id

### batchgetcontact如何获取没有信息群成员列表

{"BaseRequest":"Uin":2684027137,"Sid":"L9W0ddcaijmzhYhu","Skey":"@crypt_3bb2969_5d9682fbe6794c9437337ef278f6615c","DeviceID":"e320058942864127"},"Count":20,"List":{"UserName":"要查询的成员名" ,"EncryChatRoomId":"群名"},"UserName":"要查询的成员名","EncryChatRoomId":"群名"}]}

获得要查询的群成员列表，这里每个非好友成员有一个encrychatroomid，*我猜*

是用来解析对应用户名的，然而后来也没明白这有啥用

**Comment by reverland** [comment]
故流程为

从消息中获取群username
使用群username获取成员列表
解析收到消息的发信人username为昵称

可以设计缓存

**Comment by reverland** [comment]
如 #17 所更新的encrychatroomid只与群头像有关

**Comment by reverland** [comment]
关闭该issue，如果需要再打开
