### ISSUE TITLE
web微信如何实现at？

### ISSUE THREAD

**Issue by reverland** [HalfdogStudio/wechat-user-bot#15]
web微信似乎无法实现at？还是需要手动at？

at会有用吗？

**Comment by imtcn** [comment]
群可以艾特 会有红字提醒 ex: @reverland

**Comment by reverland** [comment]
@imtcn 实际上就是文字at，似乎是群昵称

**Comment by reverland** [comment]
如果需要考虑再打开

**Comment by lyyyuna** [comment]
我看at之后有一个 '\u2005' 不可见字符，所以表现出来像是一个空格？
'@.+?\u2005'

**Comment by reverland** [comment]
原来是这样？现在我就是在群消息中匹配一下 @用户名 @lyyyuna

**Comment by lyyyuna** [comment]
@reverland 
是在去别人的 at 回复时发现的。不过我的 at 还没有加 '\u2005'。

**Comment by kzx1025** [comment]
@lyyyuna @reverland 请问你们艾特的功能实现了吗

**Comment by lyyyuna** [comment]
@kzx1025 直接 @ + 不可见字符即可

**Comment by kzx1025** [comment]
@lyyyuna 是@+名字+u'\u2005'  这样的格式吗 我刚才试了一下 好像不行

**Comment by lyyyuna** [comment]
@kzx1025 
@+u'\u2005' +名字  这样呢

**Comment by kzx1025** [comment]
@lyyyuna 不行啊，你们试过吗 我估计艾特人的协议没这么简单，现在电脑客户端支持艾特人，网页端不支持。也不知道请求的格式是什么样的

**Comment by shiqwang** [comment]
不支持吗？？？

-- 
Shiqi Wang
Sent with Airmail

On June 20, 2016 at 11:58:40 PM, 柯 (notifications@github.com) wrote:

@lyyyuna 不行啊，你们试过吗 我估计艾特人的协议没这么简单，现在电脑客户端支持艾特人，网页端不支持。也不知道请求的格式是什么样的

**Comment by kzx1025** [comment]
@shiqwang 网页版微信不支持，所以机器人也没法支持
