### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by nexteve** [HalfdogStudio/wechat-user-bot#58]
扫完二维码报这样的错，请问是哪里的问题。
![image](https://cloud.githubusercontent.com/assets/11267282/21377144/920ce3e8-c776-11e6-8af8-58792901ef75.png)

**Comment by nexteve** [comment]
Ubuntu 16.04.1 LTS \n \l
nodejs v6.6.0

**Comment by reverland** [comment]
确实socket hang up，暂时不知道为啥。。。有空时看看

**Comment by dlyt** [comment]
我的也是

**Comment by reverland** [comment]
我。。。最近没空看。。。orz

**Comment by reverland** [comment]
@dlyt @nexteve 不知道微信为啥换了webpush的域名，应该已经修复了
